name: Call Reusable Workflow
on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: github.com/agarapunaveen/workflow-call/.github/workflows/workflow-call.yml@main
    with:
      name: "My Application"
      environment: "production"
    secrets:
      api_key: ${{ secrets.PRODUCTION_API_KEY }}
