name: Reusable Workflow Example
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
        default: "check it is working or not"
     

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Display Input
        run: echo "Deploying to ${{ inputs.message }}"
